version: "3"

services:
  nestjs_events_nestjs:
    container_name: nestjs_events_nestjs
    build: .
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 3333:3333
    networks:
      - app-network
    volumes:
      - ../:/nestjs_events:cached

  nestjs_events_postgres:
    container_name: nestjs_events_postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs_events_db
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql

networks:
  app-network:
    driver: bridge
